### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by BAREJAA** [kexinhuang12345/DeepPurpose#102]
When I try to load DeepPurpose in Google Colab, I get the following error (to do with rdkit) - 

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/site-packages/rdkit/Chem/../../../../libboost_regex.so.1.74.0)

Any help would be appreciated. 

Thanks!

**Comment by kexinhuang12345** [comment]
I am not familiar with this error. What code are you using for the colab? Have you tried to follow this: https://colab.research.google.com/drive/1eF60BwGX6PnB91vpx5dRxFa72e6-MYuZ?usp=sharing

**Comment by BAREJAA** [comment]
I tried that, but I ended up with this error - 

ImportError: cannot import name 'oneliner' from 'DeepPurpose' (unknown location)

I was previously following the pip installation instructions in the README file

**Comment by BAREJAA** [comment]
I see that this was one of the closed issues (I should have looked more closely). So as I understand, all the code needs to be executed as .py files in the code cells? Also, I do not see play.py anywhere.

**Comment by kexinhuang12345** [comment]
Oh yeah, i think you need to create a separate .py file and put the code there. It is weird that it does not work with notebook cells. Probably the sys path is going wrong. I also tried but it is not obvious to me for a simple fix with sys.path change. So you can try to use .py file first, which should also be convenient, as you can call within a cell with %%bash

**Comment by BAREJAA** [comment]
Yes, this works! Thank you! I look forward to using this now :)
