### ISSUE TITLE
Broad Repurposing Drug Name question

### ISSUE THREAD

**Issue by BAREJAA** [kexinhuang12345/DeepPurpose#103]
What do the values in the "Drug Name" column of the table produced by `models.repurpose` refer to? For example, my top hit is "5063.0", but I can't tell what drug this value refers to. I don't see it anywhere in the data table I downloaded from the Drug Repurposing Hub.

Thanks!

**Comment by kexinhuang12345** [comment]
Hey, sorry for the confusion, the Drug Name column is created for data that have IDs. But for many, when no IDs are found in the dataset, we simply generate a drug index by the "X_repurpose". You can also feed your drug name list by specifying "drug_names", a list of names matching with X_repurpose.

**Comment by BAREJAA** [comment]
So, in the table below, does "Drug Name" refer to the CID?

Drug Repurposing Result for SDHA
+------+-------------+-------------+---------------+
| Rank |  Drug Name  | Target Name | Binding Score |
+------+-------------+-------------+---------------+
|  1   |  11434515.0 |     SDHA    |      8.34     |
|  2   |  11598628.0 |     SDHA    |      7.79     |
|  3   |  11713159.0 |     SDHA    |      7.71     |

**Comment by BAREJAA** [comment]
Another question (sorry for all the questions!) - since I used the 'CNN_CNN_BindingDB_IC50' pre-trained model, does that mean the "Binding Score" column in the table above contains pIC50 values?

**Comment by kexinhuang12345** [comment]
yes, this looks like CIDs. You can specify the model to predict pIC50 or IC50 by 'convert_y = True' in default, it is set to be recovered back to the IC50 but the model is trained on pIC50

**Comment by BAREJAA** [comment]
Thanks again!
