### ISSUE TITLE
Pretrained models (IC50)

### ISSUE THREAD

**Issue by aanighoro** [kexinhuang12345/DeepPurpose#104]
Hi, what's the unit of the IC50 predictions in pretrained models? Are they perhaps pIC50 rather than IC50 values?
Actually, is there any documentation about those models that could answer similar questions?
Thanks!

**Comment by kexinhuang12345** [comment]
Hi, during training, it is all using pIC50. But you can specify conversion for adding the variable 'convert_y'. Just add a note in the readme!
