### ISSUE TITLE
Data Loader failed because RDKit2D: Failed to initialize?

### ISSUE THREAD

**Issue by KXCY-AI** [kexinhuang12345/DeepPurpose#105]
Experts, 

I tried to follow the Dataset Tutorial notebook to load data, it failed at the very beginning:
`import os

os.chdir('../')

from DeepPurpose import utils, models, dataset`

with output:

> ---------------------------------------------------------------------------

> ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/DeepPurpose/utils.py in <module>
     12 try:
---> 13         from descriptastorus.descriptors import rdDescriptors, rdNormalizedDescriptors
     14 except:

> /usr/local/lib/python3.6/dist-packages/descriptastorus/descriptors/__init__.py in <module>
      2 from .DescriptorGenerator import *
----> 3 from .rdDescriptors import *
      4 from .rdNormalizedDescriptors import *

> /usr/local/lib/python3.6/dist-packages/descriptastorus/descriptors/rdDescriptors.py in <module>
    366 
--> 367 RDKit2D()
    368 

> /usr/local/lib/python3.6/dist-packages/descriptastorus/descriptors/rdDescriptors.py in __init__(self, properties)
    359                     self.__class__.__name__,
--> 360                     "\n\t".join(failed)))
    361 

> ValueError: RDKit2D: Failed to initialize: unable to find specified properties:
	fr_Al_COO
	fr_Al_OH
	fr_Al_OH_noTert
	fr_ArN
	fr_Ar_COO
	fr_Ar_N
	fr_Ar_NH
	fr_Ar_OH
	fr_COO
	fr_COO2
	fr_C_O
	fr_C_O_noCOO
	fr_C_S
	fr_HOCCN
	fr_Imine
	fr_NH0
	fr_NH1
	fr_NH2
	fr_N_O
	fr_Ndealkylation1
	fr_Ndealkylation2
	fr_Nhpyrrole
	fr_SH
	fr_aldehyde
	fr_alkyl_carbamate
	fr_alkyl_halide
	fr_allylic_oxid
	fr_amide
	fr_amidine
	fr_aniline
	fr_aryl_methyl
	fr_azide
	fr_azo
	fr_barbitur
	fr_benzene
	fr_benzodiazepine
	fr_bicyclic
	fr_diazo
	fr_dihydropyridine
	fr_epoxide
	fr_ester
	fr_ether
	fr_furan
	fr_guanido
	fr_halogen
	fr_hdrzine
	fr_hdrzone
	fr_imidazole
	fr_imide
	fr_isocyan
	fr_isothiocyan
	fr_ketone
	fr_ketone_Topliss
	fr_lactam
	fr_lactone
	fr_methoxy
	fr_morpholine
	fr_nitrile
	fr_nitro
	fr_nitro_arom
	fr_nitro_arom_nonortho
	fr_nitroso
	fr_oxazole
	fr_oxime
	fr_para_hydroxylation
	fr_phenol
	fr_phenol_noOrthoHbond
	fr_phos_acid
	fr_phos_ester
	fr_piperdine
	fr_piperzine
	fr_priamide
	fr_prisulfonamd
	fr_pyridine
	fr_quatN
	fr_sulfide
	fr_sulfonamd
	fr_sulfone
	fr_term_acetylene
	fr_tetrazole
	fr_thiazole
	fr_thiocyan
	fr_thiophene
	fr_unbrch_alkane
	fr_urea

> During handling of the above exception, another exception occurred:

> ImportError                               Traceback (most recent call last)
<ipython-input-6-6ea3d5e19c06> in <module>
      2 os.chdir('../')
      3 
----> 4 from DeepPurpose import utils, models, dataset

> /usr/local/lib/python3.6/dist-packages/DeepPurpose/utils.py in <module>
     13         from descriptastorus.descriptors import rdDescriptors, rdNormalizedDescriptors
     14 except:
---> 15         raise ImportError("Please install pip install git+https://github.com/bp-kelley/descriptastorus and pip install pandas-flavor")
     16 from DeepPurpose.chemutils import get_mol, atom_features, bond_features, MAX_NB, ATOM_FDIM, BOND_FDIM
     17 from subword_nmt.apply_bpe import BPE

> ImportError: Please install pip install git+https://github.com/bp-kelley/descriptastorus and pip install pandas-flavor`

I believe the following libraries was installed on my server:

pandas                       1.1.5
pandas-flavor            0.2.0
DeepPurpose            0.1.1,
descriptastorus         2.3.0.2
scikit-learn                0.20.3

Anything I missed during deployment? Thank for any suggestion.

**Comment by kexinhuang12345** [comment]
Hi, i think it is an env error. Are you in the git source version? or the pip version? For pip version, you can remove the import os/ os.chdir('../') lines. But this error seems to be that the descriptastorus is not properly installed. Can you restall it again?

**Comment by kexinhuang12345** [comment]
closing for now, feel free to reopen if the problem still exists
