### ISSUE TITLE
Using DeepPurpose ForDDI

### ISSUE THREAD

**Issue by waqarkaleemkhan** [kexinhuang12345/DeepPurpose#106]
Hi, @kexinhuang12345 hope you will be doing well. I have some questions below can you please answer that.
1) Can you please provide some information that how can we use the DeepPurpose for Drug-Drug Interaction prediction.
2) Can we use data from a CSV file to train a model or just have to use the text file means did DeepPurpose support CSV.
3) What about that if I want to use the other features inputs like enzymes, targets, and pathways with smiles for drug-drug interactions can I use that, or I have to just use smiles.
Thanks

**Comment by kexinhuang12345** [comment]
Hi, for 1, you can find a case study in the readme for DDI prediction. For 2, we have a read file function. The function is here: https://github.com/kexinhuang12345/DeepPurpose/blob/8d93b94a04515ac4b806872137abba72f463f8b5/DeepPurpose/dataset.py#L60

each line is a SMILES SMILES Score. For 3, we don’t support it as DeepPurpose is formulated as an encoder-decoder framework. Where it encodes drug info from SMILES. But you can certainly leverage many codes in the DeepPurpose, for example in the encoders.py where all models are well defined.
