### ISSUE TITLE
国内连接下载不了数据，必须要vpn吗

### ISSUE THREAD

**Issue by lonngxiang** [kexinhuang12345/DeepPurpose#110]
# load AID1706 Assay Data
X_drugs, _, y = load_AID1706_SARS_CoV_3CL()

URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by futianfan** [comment]
我们会考虑解决一下。稍后给你回复。

**Comment by lonngxiang** [comment]
> 我们会考虑解决一下。稍后给你回复。

多谢，我也再看下是否是conda 源等的问题

**Comment by futianfan** [comment]
里面有个google drive, 我们稍后会调整一下。谢谢

**Comment by lonngxiang** [comment]
> 里面有个google drive, 我们稍后会调整一下。谢谢

多谢，期待

**Comment by kexinhuang12345** [comment]
hi 你可以通过这个链接下载： https://dataverse.harvard.edu/api/access/datafile/4931300
