### ISSUE TITLE
Wrong comment in the class DGL_NeuralFP

### ISSUE THREAD

**Issue by Yuhan-Fei** [kexinhuang12345/DeepPurpose#112]
Hi @kexinhuang12345 ,
     Thank you for the great works for the DTI predictions. We found you comment the class DGL_NeuralFP as GAT in encoders.py (LINE:#336. The comment said ## adapted from https://github.com/awslabs/dgl-lifesci/blob/2fbf5fd6aca92675b709b6f1c3bc3c6ad5434e96/python/dgllife/model/model_zoo/gat_predictor.py) . However, the DGL_NeuralFP is a different model apparently. Due to GAT is a very popular model for the small molecules, will you update the GAT for the Deeppurpose recently ?
Best

**Comment by kexinhuang12345** [comment]
sounds good, do you want to make a commit to it, either change the comment or adapt the code?

**Comment by kexinhuang12345** [comment]
closing for now
