### ISSUE TITLE
Request for ai cures data

### ISSUE THREAD

**Issue by chemlove** [kexinhuang12345/DeepPurpose#115]
Kexin, many thanks for this library!
It seems the CAPTCHA of https://www.aicures.mit.edu/forum can not be loaded now. So I can't get the data through email.
Can you upload the aicures_data dataset since it is used in several demo ipynb files?

> Hi, the data is from mit ai cures, you have to send an email to get it: https://www.aicures.mit.edu/forum
> Checkout the open data section in https://www.aicures.mit.edu/data

_Originally posted by @kexinhuang12345 in https://github.com/kexinhuang12345/DeepPurpose/issues/54#issuecomment-755073166_

**Comment by kexinhuang12345** [comment]
Hey, sorry about that. As I am not the organizer, I am not sure if I have the authorization to redistribute the dataset, they explicitly ask for approval on their ends. I suggest reach out to their emails? Alternatively, you can try a couple of ADME datasets in our TDC, which has similar format as in aicures: https://tdcommons.ai/single_pred_tasks/adme/
