### ISSUE TITLE
"CUDA error: device-side assert triggered" for Binary Classification

### ISSUE THREAD

**Issue by hyojin0912** [kexinhuang12345/DeepPurpose#116]
Hello, Thanks for your nice tool.

I want to make model predicting **binary** drug-target interaction.

And following Tutorial 1: Training a Drug-Target Interaction Model from Scratch,

I met error at `model.train(train, val, test)`
'RuntimeError: CUDA error: device-side assert triggered'

For binary classification, I changed toy_data/dti.txt's label into 1 or 0

This error emerges to other dataset and encoder

I upload execution ipynb, data and enviornment file that I used.
[Desktop.zip](https://github.com/kexinhuang12345/DeepPurpose/files/6881866/Desktop.zip)

Thanks 

Sincerely, Hyojin
[Desktop.zip](https://github.com/kexinhuang12345/DeepPurpose/files/6881849/Desktop.zip)

**Comment by kexinhuang12345** [comment]
Hi, i think it is because the dti txt file that you have has two DTI pairs only. Please try an example with larger dataset, for example, https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/CNN-Binary-Example-DAVIS.ipynb
