### ISSUE TITLE
Model visualization through torchsummary 

### ISSUE THREAD

**Issue by hyojin0912** [kexinhuang12345/DeepPurpose#117]
Hello, I trained DTI Model through your ipynb guide.
However, could I visualize model architecture using torchsummary?

For example, I saved Morgan & AAC encoder using Davis data.
And load trained weight. Could you guide after this?
`model = models.model_pretrained('./Morgan_AAC_Davis_model')`
`model.config`
{'input_dim_drug': 1024,
 'input_dim_protein': 8420,
 'hidden_dim_drug': 256,
 'hidden_dim_protein': 256,
 'cls_hidden_dims': [1024, 1024, 512],
 'batch_size': 256,
 'train_epoch': 50,
 'test_every_X_epoch': 20,
 'LR': 0.001,
 'drug_encoding': 'Morgan',
 'target_encoding': 'AAC',
 'result_folder': './result/',
 'binary': True,
 'num_workers': 0,
 'cuda_id': None,
 'mlp_hidden_dims_drug': [1024, 256, 64],
 'mlp_hidden_dims_target': [1024, 256, 64],
 'decay': 0}

`from torchsummary import summary` 
`summary(model, [ **??** ]) `

Thanks

**Comment by kexinhuang12345** [comment]
hi i haven't tried that before; but it seems the model parameter is just a pytorch model module. So you can call net.model if net is the deeppurpose wrapper class (e.g. net = models.model_initialize(**config)).
