### ISSUE TITLE
increasing MAX_ATOM in line 26 utils.py

### ISSUE THREAD

**Issue by sailseem** [kexinhuang12345/DeepPurpose#118]
Dear developer,
   What a great package, well, when i was running the examples 
train, val, test = data_process(X_drug, X_target, y, 
                                drug_encoding, target_encoding, 
                                split_method='random', 
                                frac=[0.7,0.1,0.2])

I got an error like this, Exception: Please increasing MAX_ATOM in line 26 utils.py, for example, MAX_ATOM=600 and reinstall it via 'python setup.py install'. The current setting is for small molecule. 

I have no idea what's that, can you help me with it?
Thanks

**Comment by kexinhuang12345** [comment]
It is because your dataset has a molecule that is more than a set number of atoms. Currently, the MPNN method works only for small molecule drugs. You can increase the MAX_ATOM in line 26 in utils.py file to the maximum number of molecules if you want to still try the MPNN implementation. Alternatively, feel free to try the DGL_GCN, DGL_GIN_* models as they are also graph neural network based

**Comment by sailseem** [comment]
but i am using the exact sample data downloaded from bindingDB, when I edited the utils.py to 600 and re-install the package, the error still there, I don't know why

**Comment by kexinhuang12345** [comment]
hi, yes i think in the newer version of the bindingDB there is a molecule that is particularly large. How did you re-install it?

**Comment by sailseem** [comment]
well, I downloaded the whole code folder and in the main folder, there is a setup.py file and I just tape in "python setup.py install" in the terminal while under the virtual environment.

**Comment by sailseem** [comment]
btw, a silly question, how to increase the memory limit in the binder-jupyter, kernel is always dead because of only 2G memory when run model.train function. Thanks a lot!

**Comment by kexinhuang12345** [comment]
Yeah that should be good. Maybe remove the pip version in case there is a version conflict. For the binder, yeah, it is a bummer, for continuous usage, we highly recommend a local copy as binder refreshes everything. Alternatively, you can also try google colab. Here is an example: https://colab.research.google.com/drive/1eF60BwGX6PnB91vpx5dRxFa72e6-MYuZ?usp=sharing
