### ISSUE TITLE
questions about usage

### ISSUE THREAD

**Issue by xnuohz** [kexinhuang12345/DeepPurpose#12]
How could I use DTBA model trained by myself to predict a new pair, and what is the inputs' format?
Thanks! :)

**Comment by kexinhuang12345** [comment]
Hi,

You can check out the example ([link](https://github.com/kexinhuang12345/DeepPurpose#case-study-3-a-framework-for-drug-target-interaction-prediction-with-less-than-10-lines-of-codes)) in the readme file, where it trains a DTBA model from scratch, and you can specify any of the parameters. 

For the inputs' format, basically, the input drug is an array of drug SMILES, and the input target is an array of protein amino acids. Another easy way to load data is using our dataset loader function to read from txt. A tutorial is provided [here](https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/load_data_tutorial.ipynb).

If you want to train a new model using customized data and generate repurposing/screening drug candidate list, you can also checkout this [demo](https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/case-study-III-Drug-Repurposing-with-Customized-Data.ipynb), where the entire process is wrapper into one line and will print out the result for you.

Let me know if you have more questions!
