### ISSUE TITLE
Misbehavior of utils.mpnn_collate_func under DDI prediction setting

### ISSUE THREAD

**Issue by CapFreddy** [kexinhuang12345/DeepPurpose#120]
Under DDI prediction setting, both drugs in the drug pair (i.e., the first 2 items of the input x) should be processed by mpnn_feature_collate_func, yet currently only the first is processed, causing a size error later on.

DDI_flag should be introduced as an argument to include the DDI setting.

**Comment by kexinhuang12345** [comment]
interesting. Thanks for the headsup. Yeah. majority of our dataset in small molecule is relatively small. so single gpu should handle majority of cases
