### ISSUE TITLE
how to apply model

### ISSUE THREAD

**Issue by sailseem** [kexinhuang12345/DeepPurpose#122]
Dear Dr.huang,
     Thank you for providing such a great package, well, i am quite new to all of this. Assumed that i got the well trained model for drug and target binding based on bindingDB database. And, i can upload like 100 drugs smiles by using dataset.read_file_target_sequence (drugs.txt),  at the same time, upload 100 targets using same dataset.read_file_target_sequence (targets.txt).   But, how to apply this to get a possible binding score of each pair?    
   like   "model.predict(drug,targets)"     but this returns TypeError: predict() takes 2 positional arguments but 3 were given

I am sorry for your time to look at such a silly question, but thanks a lot, anyway
Bests,
fan

**Comment by kexinhuang12345** [comment]
for virtual screening mode, you should put target as three same protein sequence as a list, instead of just one. So

['MLGRNTWKTSAFSFLVEQMWAPLWSRSMRPGRWCSQRSCAWQTSNNTLHPLWTVPVSVPGGTRQSPINIQWRDSVYDPQLKPLRVSYEAASCLYIWNTGYLFQVEFDDATEASGISGGPLENHYRLKQFHFHWGAVNEGGSEHTVDGHAYPAELHLVHWNSVKYQNYKEAVVGENGLAVIGVFLKLGAHHQTLQRLVDILPEIKHKDARAAMRPFDPSTLLPTCWDYWTYAGSLTTPPLTESVTWIIQKEPVEVAPSQLSAFRTLLFSALGEEEKMMVNNYRPLQPLMNRKVWASFQATNEGTRS'] * 3

**Comment by sailseem** [comment]
Thanks, one more question. Cause you choose the kd value from bindingDB as input? Normally, the lower Kd means the high affinity. What's the meaning of the binding score? Same as Kd? or they are different? What's the normal range of binding score? How big or small should consider as a good binding affinity? Thanks

**Comment by kexinhuang12345** [comment]
Hi, yes, it is all depended on the training data. If the training data is Kd, then the inference value is all in Kd. I think in the one-liner mode, it is Kd, so lower the better. You can also transform it to pKd by setting convert_y. Note there are also a couple of models that are in IC50.

**Comment by sailseem** [comment]
sorry to re-confirm this, by using the pre-trained model like virtual screen, the binding score was ranking from high to low, feels like, the top score equals to best affinity, why you chose that way to interpret data?
