### ISSUE TITLE
graph neural network based models for DTI - Google Colab

### ISSUE THREAD

**Issue by rjd55** [kexinhuang12345/DeepPurpose#123]
Hi, I want to use the graph compound encodings (DGL_GCN, DGL_NeuralFP, etc.) for DTI and I am using Google Colab to do this. I am having a problem with installing dgllife. I have tried adding dgllife and dgl to the environment.yml file ([environment.txt](https://github.com/kexinhuang12345/DeepPurpose/files/7099367/environment.txt)), but it doesn't work. Please can you advise what change I should make?

Here is an example of the [NPASS_DGL_GCN_1.txt](https://github.com/kexinhuang12345/DeepPurpose/files/7099422/NPASS_DGL_GCN_1.txt) model I want to run, does everything look okay?

Perhaps @hima111997 you can help? Is this a Google Colab specific problem?

Thank you.

**Comment by kexinhuang12345** [comment]
I think a better place to ask this question is at DGL forum. They should have experiences in using DGL in google colab.
