### ISSUE TITLE
drug and target names

### ISSUE THREAD

**Issue by sailseem** [kexinhuang12345/DeepPurpose#124]
Dear Dr.Huang,
   Sorry to bother you again, I am using the pre-trained model to predict DTI in my dataset. Well, I am wondering can I change the default target names, like target 1, 2,3,4 to some column in the input csv files. Like showing below, each gene instead of target1,2,3.....

Thanks in advance!

y_pred = models.virtual_screening(X_drug, X_target, net)

virtual screening...
Drug Target Interaction Prediction Mode...
in total: 1686 drug-target pairs
encoding drug...
unique drugs: 1
encoding protein...
unique target sequence: 1676
Done.
predicting...
---------------
Virtual Screening Result
+------+-----------+-------------+---------------+
| Rank | Drug Name | Target Name | Binding Score |
+------+-----------+-------------+---------------+
|  1   | Drug 1616 | Target 1616 |     11.68     |
|  2   |  Drug 464 |  Target 464 |     11.63     |
|  3   |  Drug 976 |  Target 976 |     11.57     |
|  4   | Drug 1488 | Target 1488 |     11.54     |
|  5   | Drug 1360 | Target 1360 |     11.51     |
|  6   |  Drug 848 |  Target 848 |     11.50     |
|  7   |  Drug 592 |  Target 592 |     11.49     |
|  8   |  Drug 336 |  Target 336 |     11.45     |
|  9   |  Drug 720 |  Target 720 |     11.45     |
|  10  |  Drug 208 |  Target 208 |     11.38     |
checkout ./result/virtual_screening.txt for the whole list

![image](https://user-images.githubusercontent.com/72428172/133640233-6f3da475-0f83-47c6-9385-be750e854f3e.png)

**Comment by kexinhuang12345** [comment]
yes, you can specify in the `y_pred = models.virtual_screening(X_drug, X_target, drug_names = X, target_names = X, net)`

**Comment by smruti241** [comment]
Hi @sailseem i saw your post and I am willing to know your code and input file. Can you please share your code once? I wanted to rectify once. Thanks!!!
