### ISSUE TITLE
"Molecules not found and change to zero vectors.." error message

### ISSUE THREAD

**Issue by rjd55** [kexinhuang12345/DeepPurpose#125]
Hi Kexin,

I am trying to train a model using the 'MPNN' drug encoding. I get error messages that say "Molecules not found and change to zero vectors.." and "Can't kekulize mol". I am getting nan losses, is this due to these molecules resulting in nan inputs? Is there a way to skip over these DTI pairs or to find out which ones they are?

Many thanks,

Becky

**Comment by futianfan** [comment]
can you share the code you run?
