### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by imraaqeel** [kexinhuang12345/DeepPurpose#131]
(base) C:\Users\Dr. Abdul Majid>pip install git+https://github.com/bp-kelley/descriptastorus
Collecting git+https://github.com/bp-kelley/descriptastorus
  Cloning https://github.com/bp-kelley/descriptastorus to c:\users\dr9ee7~1.abd\appdata\local\temp\pip-req-build-pk5xf6sy
  Running command git clone -q https://github.com/bp-kelley/descriptastorus 'C:\Users\DR9EE7~1.ABD\AppData\Local\Temp\pip-req-build-pk5xf6sy'
  fatal: unable to access 'https://github.com/bp-kelley/descriptastorus/': Could not resolve host: github.com
ERROR: Command errored out with exit status 128: git clone -q https://github.com/bp-kelley/descriptastorus 'C:\Users\DR9EE7~1.ABD\AppData\Local\Temp\pip-req-build-pk5xf6sy' Check the logs for full command output.

**Comment by kexinhuang12345** [comment]
This seems to be resolved in emails.

**Comment by kexinhuang12345** [comment]
feel free to reopen

**Comment by imraaqeel** [comment]
yes it has resolved. It was proxy issue.
