### ISSUE TITLE
About Pretrain_model

### ISSUE THREAD

**Issue by Cyy1216** [kexinhuang12345/DeepPurpose#132]
You write in guideline:
Now, we can call the repurpose function. After feeding the necessary inputs, it will print a list of repurposed drugs ranked on its affinity to the target protein. The convert_y parameter should be set to be False when the ranking is ascending (i.e. lower value -> higher affinity) due to the log transformation, vice versus.

If I use 
`net = models.model_pretrained(model = 'CNN_CNN_BindingDB')` 
and 
`score = models.virtual_screening(drugs, proteins, net, drugs_name, proteins_name)` to predict the DTA
 Does the higher the score mean the higher the affinity level?
I feel confusing about it

**Comment by kexinhuang12345** [comment]
Here, in default, the score is lower the better. If you want to flip the direction, you could use the convert_y parameter.

**Comment by Cyy1216** [comment]
> Here, in default, the score is lower the better. If you want to flip the direction, you could use the convert_y parameter.
models.virtual_screening  is also the score is lower the better？really？
