### ISSUE TITLE
about virtual screen

### ISSUE THREAD

**Issue by Cyy1216** [kexinhuang12345/DeepPurpose#134]
Here, in default, the score is lower the better. If you want to flip the direction, you could use the convert_y parameter.

_Originally posted by @kexinhuang12345 in https://github.com/kexinhuang12345/DeepPurpose/issues/132#issuecomment-995425295_

**Comment by Cyy1216** [comment]
`models.virtual_screening` is also the score is lower the better？really？
but why I use it to predict no-interaction pairs and interaction pairs respectively, interaction pairs have more higher scores?

**Comment by albertma-evotec** [comment]
docking scores are predicted binding free energy hence are negative. More negative = better

**Comment by Cyy1216** [comment]
> docking scores are predicted binding free energy hence are negative. More negative = better

thank you very much
