### ISSUE TITLE
How do I use utils.data_process to make random train, val, test subsets?

### ISSUE THREAD

**Issue by rjd55** [kexinhuang12345/DeepPurpose#138]
Hi, I'd like to train and evaluate a Drug Target Binding Affinity model multiple times on randomly assigned train, val, test subsets. How do I do this with `data_process`? I see that with these settings, I am getting the same train, val, test sets each time:

```
train, val, test = data_process(X_drugs, X_targets, y, 
                                drug_encoding, target_encoding, 
                                split_method='random',frac=[0.85,0.1,0.05], random_seed = 2)
```
Cheers

**Comment by kexinhuang12345** [comment]
Hi, did you change the random_seed?
