### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by yuanenming** [kexinhuang12345/DeepPurpose#14]
https://github.com/kexinhuang12345/DeepPurpose/blob/6016a833de66bc56fe3a81e4c0f482b1624d970a/DeepPurpose/models.py#L757

function `test_` returns 5 items not 4 when `binary` is `True`

this line should be:
```python
				auc, auprc, f1, log_loss, logits = self.test_(testing_generator, model_max, test = True)

```

**Comment by kexinhuang12345** [comment]
Good catch! I think it is created through a recent [PR request;](https://github.com/kexinhuang12345/DeepPurpose/pull/13) I would add a new unit test for binary classification in the future. It should be [fixed now](https://github.com/kexinhuang12345/DeepPurpose/commit/b6eb188d6ec69137c211b16673037f498f8ad45b).
