### ISSUE TITLE
Feature request: alternative data download options for Chinese users

### ISSUE THREAD

**Issue by riversdark** [kexinhuang12345/DeepPurpose#140]
Hi, thanks for creating this great package!

I'm a user from China and I saw that many data processing functions download data from Google drive. Since Google is blocked in China, these function calls always time out, which makes the functionalities unusable. It would be nice if the data can have a secondary storage option, and if connection to the first source times out, the function calls can also try another unblocked source. Or maybe the data can be stored somewhere else that's accessible.

**Comment by futianfan** [comment]
we will consider it. thanks!!

**Comment by futianfan** [comment]
we have updated the google drive link to a github link. Now it works for Chinese users. thanks for your issues!!

**Comment by riversdark** [comment]
Wow that was fast :D Thanks!
