### ISSUE TITLE
Side effects prediction 

### ISSUE THREAD

**Issue by greg217** [kexinhuang12345/DeepPurpose#145]
Could you provide code examples on using DeepPurpose for Side effects predictions?

**Comment by kexinhuang12345** [comment]
For drug-drug interaction side effect, checkout https://github.com/kexinhuang12345/DeepPurpose#case-study-1c-a-framework-for-drug-drug-interaction-prediction-with-less-than-10-lines-of-codes

For a single drug side effect, you can use compound property prediction, checkout https://github.com/kexinhuang12345/DeepPurpose#case-study-1b-a-framework-for-drug-property-prediction-with-less-than-10-lines-of-codes
