### ISSUE TITLE
download_BindingDB() 404 error

### ISSUE THREAD

**Issue by Jin0331** [kexinhuang12345/DeepPurpose#146]
Hi,

Changed as data in Binding_All.tsv was updated in the download_BindingDB() function. 

Please correct it.

```'https://www.bindingdb.org/bind/downloads/BindingDB_All_2021m11.tsv.zip'``` to ```https://www.bindingdb.org/rwd/bind/chemsearch/marvin/SDFdownload.jsp?download_file=/bind/downloads/BindingDB_All_2022m7.tsv.zip```

**Comment by futianfan** [comment]
we update it. thanks!!
