### ISSUE TITLE
Binding scores

### ISSUE THREAD

**Issue by Jameel9** [kexinhuang12345/DeepPurpose#150]
Dear Sir 

I hope you are doing well

I did a virtual screening using a pretrained model (the code is shown below) and got a result table in which the binding scores are sorted in a descending scale (also shown below). what is the unit of these scores? (kd?). And why not sorted from lower to higher values?

Thanks 

![code](https://user-images.githubusercontent.com/95760030/189531371-1edcb3f3-27f7-4c37-80c9-ca8d717a8a28.png)
![scores](https://user-images.githubusercontent.com/95760030/189531373-e58f9d2d-07a4-4e65-b164-fb6f20e58889.png)

**Comment by kexinhuang12345** [comment]
Hi yes, without convert_y, it is in pKd,  and with convert_y, it is the raw score. But in both cases, the rank should be the same.
