### ISSUE TITLE
Error when using DGL_GCN to run DTI model

### ISSUE THREAD

**Issue by yrq3027** [kexinhuang12345/DeepPurpose#151]
Hello, I got below errors when constructing DTI predicting model using GCN implemented in DeepPurpose (DGL) both in 1 gpu and 3 gpus.

Drug Target Interaction Prediction Mode...
in total: 270492 drug-target pairs
encoding drug...
unique drugs: 216462
encoding protein...
unique target sequence: 1914
splitting dataset...
Done.
Let's use 1 GPU!
--- Data Preparation ---
--- Go for Training ---
Traceback (most recent call last):
  File "Pharos_DeepPurpose_clf_demo.py", line 184, in <module>
    trainModel(coding)
  File "Pharos_DeepPurpose_clf_demo.py", line 177, in trainModel
    model.train(train, val, test)
  File "/home/data/aidd/DeepPurpose/DeepPurpose/DTI.py", line 436, in train
    score = self.model(v_d, v_p)
  File "/home/AIDD/anaconda3/envs/DeepPurpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data/aidd/DeepPurpose/DeepPurpose/DTI.py", line 52, in forward
    v_f = torch.cat((v_D, v_P), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1024 but got size 2 for tensor number 1 in the list.

**Comment by yrq3027** [comment]
I think this may caused by some coding problem in the drug_coding function in  /DeepPurpose/utils.py
![image](https://user-images.githubusercontent.com/46614261/190955706-2d36f887-348a-4a85-a29b-3524137cd7cf.png)

**Comment by kexinhuang12345** [comment]
Hi, is the demo code working on your end? or can you send the script?

**Comment by yrq3027** [comment]
Thank you for the reply, I cannot running the demo GNN code with same error. Followed is my script.  I just changed the data_loader for my own dataset. I find that after GNN coding, drug_coding is still SMILES.


import os
import pandas as pd
import numpy as np

import DeepPurpose.DTI as models
from DeepPurpose.utils import *
from DeepPurpose.dataset import *
from DeepPurpose import utils, DTI, dataset

CODING_TYPE = ["0", "1", "2",]

def dataLoader():
    
    X_drugs, X_targets, y = dataset.load_Pharos(binary=True)
    return X_drugs, X_targets, y

def createModel(coding):
    
    X_drugs, X_targets, y = dataLoader()
    
    if coding == "0":
        
        drug_encoding = 'Morgan'
        target_encoding = 'AAC'
        train, val, test = utils.data_process(X_drugs, X_targets, y, 
                                drug_encoding, target_encoding, 
                                split_method='random',frac=[0.7,0.1,0.2],
                                random_seed = 1)
        config = generate_config(drug_encoding = drug_encoding, 
                         target_encoding = target_encoding, 
                         cls_hidden_dims = [1024,1024,512], 
                         train_epoch = 150, 
                         LR = 0.001, 
                         batch_size = 4096,
                         cnn_target_filters = [32,64,96],
                         cnn_target_kernels = [4,8,12]
                        )
        model = models.model_initialize(**config)
    
    if coding == "1":
        
        drug_encoding = 'MPNN'
        target_encoding = 'Transformer'
        train, val, test = utils.data_process(X_drugs, X_targets, y, 
                                drug_encoding, target_encoding, 
                                split_method='random',frac=[0.7,0.1,0.2],
                                random_seed = 1)
        config = utils.generate_config(drug_encoding = drug_encoding, 
                         target_encoding = target_encoding, 
                         cls_hidden_dims = [1024,1024,512], 
                         train_epoch = 150, 
                         LR = 0.001, 
                         batch_size = 1024,
                         hidden_dim_drug = 128,
                         mpnn_hidden_size = 128,
                         mpnn_depth = 3, 
                         cnn_target_filters = [32,64,96],
                         cnn_target_kernels = [4,8,12]
                        )
        model = models.model_initialize(**config)
    
    if coding == "2":
        
        drug_encoding = 'DGL_GCN'
        target_encoding = 'CNN'
        train, val, test = utils.data_process_gnn(X_drugs, X_targets, y, 
                                drug_encoding, target_encoding, 
                                split_method='random',frac=[0.7,0.1,0.2],
                                random_seed = 1)
        config = utils.generate_config(drug_encoding = drug_encoding, 
                         target_encoding = target_encoding, 
                         cls_hidden_dims = [1024,1024,512], 
                         train_epoch = 150, 
                         LR = 0.001, 
                         batch_size = 1024,
                         hidden_dim_drug = 128,
                         mpnn_hidden_size = 128,
                         mpnn_depth = 3, 
                         cnn_target_filters = [32,64,96],
                         cnn_target_kernels = [4,8,12]
                        )
        model = models.model_initialize(**config) 

def trainModel(coding):
    
    train, val, test, drug_encoding, target_encoding, model = createModel(coding)
    model.train(train, val, test)
    model.save_model('./Pharos_model/'+drug_encoding+"-"+target_encoding+"_clf")
    
if __name__ == "__main__":
    
    for coding in CODING_TYPE:
        
        trainModel(coding)

![image](https://user-images.githubusercontent.com/46614261/192129824-8f3b924b-6d74-4964-a2ee-ca92275ff979.png)
