### ISSUE TITLE
Possible typo in the initialization of the MPNN encoder

### ISSUE THREAD

**Issue by diliadis** [kexinhuang12345/DeepPurpose#156]
Hello,

From what I understand, the only two hyperparameters of the MPNN encoder are the **mpnn_depth** and **mpnn_hidden_size**. Both parameters are also supported in the initialization of the config (by calling **generate_config** ). I noticed that even though the **mpnn_hidden_size** is shown as something you can control using the **mpnn_hidden_size** parameter (for example, in the _MPNN_CNN_Davis.ipynb_ and _MPNN_CNN_Kiba.ipynb_ notebooks), the actual initialization of the MPNN encoder (in the _DTI.py_ and _DDI.py_ files) uses the value of  **hidden_dim_drug** instead. Is this a typo, or is the mpnn_hidden_size parameter something that should be removed from **generate_config( )**?

Thanks,
Dimitris

**Comment by kexinhuang12345** [comment]
Good catch! Yes, please consider removing from the generate_config. Note that our MPNN is a dense graph implementation without more recent message passing framework, so we suggest you use the DGL_GCN encoders instead. Hope this helps!
