### ISSUE TITLE
The GNN model does not work properly

### ISSUE THREAD

**Issue by kangcheng-2022** [kexinhuang12345/DeepPurpose#159]
hello, kexin huang.
thanks for your works.
when i use gnn models to do prediction, this error occur: ValueError: Using a target size (torch.Size([128])) that is different to the input size (torch.Size([256])) is deprecated. Please ensure they have the same size.
other model can run properly. i look at your code of  gnn model, i find that you use dgl-life model. Then i check this module in github, i find this model have updated now. i don't know if it has an impact for you model.
this is my code:
from DeepPurpose.utils import *
from DeepPurpose.dataset import *
from DeepPurpose import dataset
from DeepPurpose import CompoundPred as models
PATH = 'my_Data/tastes_split/Bitterness_binary.txt'
X_drugs, _, y = dataset.read_file_training_dataset_bioassay(PATH)

drug_encoding = 'DGL_GCN'

#import torch
#torch.backends.cudnn.enabled = False

train, val, test = data_process(X_drug = X_drugs, y = y, 
                drug_encoding = drug_encoding,
                split_method='random', 
                random_seed = 1)

config = generate_config(drug_encoding = drug_encoding, 
                        cls_hidden_dims = [512], 
                        train_epoch = 30, 
                        LR = 0.001, 
                        batch_size = 128,
                        )
model = models.model_initialize(**config)
model.train(train, val, test)

**Comment by songyu2022** [comment]
this is the complete error:
ValueError                                Traceback (most recent call last)
 in 
     36                         )
     37 model = models.model_initialize(**config)
---> 38 model.train(train, val, test)

/data/songyu/softwareInstall/Anaconda3/envs/DeepPurpose/lib/python3.7/site-packages/DeepPurpose/CompoundPred.py in train(self, train, val, test, verbose)
    363                                         n = torch.squeeze(score, 1)
    364                                         loss = loss_fct(n, label)
--> 365                                 loss_history.append(loss.item())
    366 
    367                                 opt.zero_grad()

/data/songyu/softwareInstall/Anaconda3/envs/DeepPurpose/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/data/songyu/softwareInstall/Anaconda3/envs/DeepPurpose/lib/python3.7/site-packages/torch/nn/modules/loss.py in forward(self, input, target)
    617 
...
-> 3088             "Please ensure they have the same size.".format(target.size(), input.size())
   3089         )
   3090 

ValueError: Using a target size (torch.Size([128])) that is different to the input size (torch.Size([256])) is deprecated. Please ensure they have the same size.

**Comment by kexinhuang12345** [comment]
Maybe it is because you are using multiple GPUs? could you try single GPU?

**Comment by kangcheng-2022** [comment]
> Maybe it is because you are using multiple GPUs? could you try single GPU?

yes, you are right. i did it. it's OK now, thank you
