### ISSUE TITLE
Add Directed MPNN?

### ISSUE THREAD

**Issue by markcheung** [kexinhuang12345/DeepPurpose#19]
Can Directed MPNN, model from this paper (https://pubs.acs.org/doi/10.1021/acs.jcim.9b00237) be added? Code is here: https://github.com/chemprop/chemprop/blob/master/chemprop/models/mpn.py .
 
Its updates for the message passing are on the edges, so it's slightly different from MPNN.

**Comment by kexinhuang12345** [comment]
Hi, yes, it has been in our backlog. Would be included in a month or so. We are currently working on more tasks and then expand more models. Will keep you posted here when D-MPNN is added.

**Comment by markcheung** [comment]
Sounds good, thanks!
