### ISSUE TITLE
How to use DeepPurpose for Virtual screening?

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#24]
Greetings sir,

I want to use DeepPurpose for Virtual screening using drugs downloaded from databases with a certain protein. 

Can you give me information on how to do this? such as the preparation of drugs and the protein?

Thanks

**Comment by kexinhuang12345** [comment]
Hi, do you have high throughput screening data for this protein? if so, you can use the drug property prediciton mode; if not, you can use the DTI mode.

**Comment by hima111997** [comment]
Do you mean using code like the one found in this notebook?
https://github.com/kexinhuang12345/DeepPurpose/blob/master/Tutorial_1_DTI_Prediction.ipynb

I noticed that in the notebook, Virtual screening used many drugs and many proteins. but the videos I watched on youtube that used autodock vina used one protein and many drugs. 
Which way is the right way for virtual screening?

thanks

**Comment by kexinhuang12345** [comment]
hi, so DTI is to train upon a large set of proteins and drugs to generalize over unseen target and drugs. For virtual screening, you can also specify the one protein and many drugs. Just need to replicate each protein to a list of proteins.

**Comment by hima111997** [comment]
so it will be like this:

drug_1 protein_1
drug_2 protein_1
drug_3 protein_1
...

right?

**Comment by kexinhuang12345** [comment]
Yes, you are right.

On Fri, Sep 25, 2020 at 14:20 hima111997 <notifications@github.com> wrote:

>
>
> so it will be like this:
>
>
> drug_1 protein_1
>
>
> drug_2 protein_1
>
>
> drug_3 protein_1
>
>
> ...
>
>
> right?
>
>
>
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kexinhuang12345_DeepPurpose_issues_24-23issuecomment-2D699160597&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=mSUc4HXjofxNLrCs5NQSL_iCb4_axPk57vpqawvj1G0&s=mgtIWD7rJVf7zv6UQ8k-aPXBpd0G6duDbd2I7Ag2iqk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGUB5AZ3JPMPKBMC5R2F33DSHUCQ5ANCNFSM4R2HCJQQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=mSUc4HXjofxNLrCs5NQSL_iCb4_axPk57vpqawvj1G0&s=jzzhKfziz73vQbEU-uxuZDRiO72TdxkvGfM8OoogEuA&e=>
> .
>
>
> --

Best Regards,

*Kexin Huang*

New York University
Mobile (USA): +1 917-558-1909
Email: kexin.huang@nyu.edu

**Comment by hima111997** [comment]
so can I use a pre-trained model or should I train a model with the same input?

for example:
a model trained on many proteins and many drugs --> use it to predict the binding between many drugs and one protein
OR
a model trained on many drugs and one protein -->  use it to predict the binding between many drugs and one proteinAlso 

Also, are there any pre-trained models for the second choice (if it is the correct one) ? or should I modify a dataset to be the same as what I want to do (many drugs and one protein)?

**Comment by kexinhuang12345** [comment]
Hi, the use case of DTI is when there is no screening data available for the testing drugs and targets so that we can rely on the model that is trained on a large amount of DTI pairs to learn chemical semantics and generalize over unseen new drugs/targets. But for use case that is specific for one target protein of interest and has screening data (many drugs and their affinity scores with the protein). then it is a good idea to train a drug property prediction model (DeepPurpose.CompoundPred); and then use it to predict new drugs. so there is no protein information involved. That said, you can still try DTI model for the screening data given you have the protein sequence; although it is extra complexity since you need to use a separate protein encoder. so i would suggest use drug property prediction directly.

**Comment by hima111997** [comment]
In my case, I have one protein and a large number of drugs without their affinity scores. From your last comment I understood that I should use the DTI with pretrained models, right? 
And the input data will be as follows:Drug1  protein1Drug2  protein1
Drug3  protein1etc... Is that right? 
Sent from Yahoo Mail on Android 
 
  On الاثنين, سبتمبر ٢٨, ٢٠٢٠ at ١٢:٢٨ ص, Kexin Huang<notifications@github.com> wrote:   


Hi, the use case of DTI is when there is no screening data available for the testing drugs and targets so that we can rely on the model that is trained on a large amount of DTI pairs to learn chemical semantics and generalize over unseen new drugs/targets. But for use case that is specific for one target protein of interest and has screening data (many drugs and their affinity scores with the protein). then it is a good idea to train a drug property prediction model (DeepPurpose.CompoundPred); and then use it to predict new drugs. so there is no protein information involved. That said, you can still try DTI model for the screening data given you have the protein sequence; although it is extra complexity since you need to use a separate protein encoder. so i would suggest use drug property prediction directly.

**Comment by kexinhuang12345** [comment]
Yes, if you just want to get the prediction score.

**Comment by hima111997** [comment]
Thank you so much sir. 
Just a question. Is there a way to get the score for the binding between drugs and a certain domain from the protein. For example,  adding this sequence only (not the whole protein sequence) in the input file?

Sent from Yahoo Mail on Android 
 
  On الاثنين, سبتمبر ٢٨, ٢٠٢٠ at ٢:١٩ ص, Kexin Huang<notifications@github.com> wrote:   


Yes, if you just want to get the prediction score.

**Comment by kexinhuang12345** [comment]
Hey, It is not currently supported. But I think it is an interesting point and I will look into it.

**Comment by hima111997** [comment]
Thank you so much for your support.

**Comment by kexinhuang12345** [comment]
great, let me know if you have more question and closing for now.
