### ISSUE TITLE
error in calcPubChemFingerPart1

### ISSUE THREAD

**Issue by jchartove** [kexinhuang12345/DeepPurpose#26]
When running data_process on the BindingDB dataset, I'm getting the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-ea0ef9f36ff3> in <module>
      1 train, val, test = utils.data_process(X_drugs, X_targets, y, 
      2                                 drug_encoding, target_encoding,
----> 3                                 split_method='cold_drug',frac=[0.7,0.1,0.2])

~\Dropbox\Work\insight\omic\DeepPurpose-omic\DeepPurpose\utils.py in data_process(X_drug, X_target, y, drug_encoding, target_encoding, split_method, frac, random_seed, sample_frac, mode, X_drug_, X_target_)
    418 
    419         if DTI_flag:
--> 420                 df_data = encode_drug(df_data, drug_encoding)
    421                 df_data = encode_protein(df_data, target_encoding)
    422         elif DDI_flag:

~\Dropbox\Work\insight\omic\DeepPurpose-omic\DeepPurpose\utils.py in encode_drug(df_data, drug_encoding, column_name, save_column_name)
    265                 df_data[save_column_name] = [unique_dict[i] for i in df_data[column_name]]
    266         elif drug_encoding == 'Pubchem':
--> 267                 unique = pd.Series(df_data[column_name].unique()).apply(calcPubChemFingerAll)
    268                 unique_dict = dict(zip(df_data[column_name].unique(), unique))
    269                 df_data[save_column_name] = [unique_dict[i] for i in df_data[column_name]]

~\anaconda3\envs\multiPurpose\lib\site-packages\pandas\core\series.py in apply(self, func, convert_dtype, args, **kwds)
   4198             else:
   4199                 values = self.astype(object)._values
-> 4200                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   4201 
   4202         if len(mapped) and isinstance(mapped[0], Series):

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

~\Dropbox\Work\insight\omic\DeepPurpose-omic\DeepPurpose\pybiomed_helper.py in calcPubChemFingerAll(s)
   3377 
   3378 def calcPubChemFingerAll(s):
-> 3379     mol = Chem.MolFromSmiles(s)
   3380     AllBits=[0]*881
   3381     res1=list(calcPubChemFingerPart1(mol).ToBitString())

~\Dropbox\Work\insight\omic\DeepPurpose-omic\DeepPurpose\pybiomed_helper.py in calcPubChemFingerPart1(mol, **kwargs)
   2690       if count == 0:
   2691         res[i + 1] = mol.HasSubstructMatch(patt)
-> 2692       else:
   2693         print('ne')
   2694         matches = mol.GetSubstructMatches(patt)

AttributeError: 'NoneType' object has no attribute 'GetSubstructMatches'

**Comment by kexinhuang12345** [comment]
Hi Julia, this is similar error with the quasi-seq, i write a workaround to resolve it in the recent commit.
