### ISSUE TITLE
Why cant i run the library on Google Colab?

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#29]
Greetings sir,

I tried to run DeepPuropose library on Google Colab, but I could not do it.

Could you please provide some instructions to install it on colab?

the link to google Colab: https://colab.research.google.com/drive/1eF60BwGX6PnB91vpx5dRxFa72e6-MYuZ?usp=sharing

I tried to install anaconda following these steps: https://towardsdatascience.com/conda-google-colab-75f7c867a522

Thanks

**Comment by kexinhuang12345** [comment]
Hey, I haven't tried that before and it looks like it is a compatibility issue between conda and google colab? so it is able to get into the DeepPurpose library, just the colab env is not set up. I will put this in the feature backlog.

**Comment by hima111997** [comment]
I managed to run DeepPurpose on Colab

This is the link containing steps:
https://colab.research.google.com/drive/1eF60BwGX6PnB91vpx5dRxFa72e6-MYuZ?usp=sharing

**Comment by kexinhuang12345** [comment]
Hi, @hima111997  thanks a lot! i would move it to the README, in case anyone else wants to try it.
