### ISSUE TITLE
How to use DeepPurpose with a protein complex consisting of two chains?

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#35]
Greetings,

Is there a way to use DeepPurpose with a protein complex consisting of two chains for drug repurposing? For Example, Should I add both chains in one file so it see them as one protein?

Thanks

**Comment by kexinhuang12345** [comment]
Hi, this is currently not supported for the One Liner Mode as the training dataset we use consists of only one protein sequence. However, it can still generate a prediction score if you concatenate them into one protein sequence. But ideally, if you have training data about these protein complexes, then, train a new DeepPurpose model from scratch should work great.

**Comment by hima111997** [comment]
Okay thank you for your help

Sent from Yahoo Mail on Android 
 
  On الأربعاء, أكتوبر ٢٨, ٢٠٢٠ at ١٠:٥٨ م, Kexin Huang<notifications@github.com> wrote:   


Hi, this is currently not supported for the One Liner Mode as the training dataset we use consists of only one protein sequence. However, it can still generate a prediction score if you concatenate them into one protein sequence. But ideally, if you have training data about these protein complexes, then, train a new DeepPurpose model from scratch should work great.
