### ISSUE TITLE
found conflicts while installing the environment

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#36]
while installing the environment, it gave me conflicts. 
I have anaconda version 4.8.2

![image](https://user-images.githubusercontent.com/55895327/97449125-06ee2500-193a-11eb-9449-988bff2df78f.png)

How can I solve them?

**Comment by kexinhuang12345** [comment]
Hi, did you create a virtual env specifically for DeepPurpose?  ``conda env create -f environment.yml`` this line should create a virtual env with all the required packages for you.

**Comment by hima111997** [comment]
Conda env create -f environment.yml is the line that produced the conflicts

Sent from Yahoo Mail on Android 
 
  On الأربعاء, أكتوبر ٢٨, ٢٠٢٠ at ١٠:٥٥ م, Kexin Huang<notifications@github.com> wrote:   


Hi, did you create a virtual env specifically for DeepPurpose? conda env create -f environment.yml this line should create a virtual env with all the required packages for you.

**Comment by kexinhuang12345** [comment]
That's weird. Then can you try this:

```
conda create -n DeepPurpose python=3.6
conda install -c conda-forge rdkit
Pip install torch
pip install scikit-learn
pip install git+https://github.com/bp-kelley/descriptastorus
pip install pandas-flavor
pip install subword-nmt
pip install wget
pip install lifelines
pip install prettytable
pip install --upgrade ipykernel
```

**Comment by hima111997** [comment]
while trying to install torch, it gave me this error:

![image](https://user-images.githubusercontent.com/55895327/97538219-b96cc900-19c8-11eb-8690-44ff5031d8ac.png)

**Comment by hima111997** [comment]
i managed to install it.
But another error came when I trie this command:

from DeepPurpose import oneliner
from DeepPurpose.dataset import *
oneliner.repurpose(*load_SARS_CoV2_Protease_3CL(), *load_antiviral_drugs(no_cid = True))

![image](https://user-images.githubusercontent.com/55895327/97564617-82f57500-19ed-11eb-834c-3893672385a6.png)

**Comment by kexinhuang12345** [comment]
Hi, can you pull the updated version and try again? there was a bug but is fixed

**Comment by hima111997** [comment]
Thanks it worked
