### ISSUE TITLE
what does "Explicit valence for atom # 1 N, 4, is greater than permitted Molecules not found and change to zero vectors.." mean?

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#37]
![image](https://user-images.githubusercontent.com/55895327/97697315-82bdae00-1aaf-11eb-8a35-f86e162427cb.png)

And this message: rdkit not found for this smiles
![image](https://user-images.githubusercontent.com/55895327/97698163-c95fd800-1ab0-11eb-92c6-00a0b0601538.png)

**Comment by kexinhuang12345** [comment]
Hi this is some warning by RDKit, you can just ignore them.

**Comment by kexinhuang12345** [comment]
Also, for the molecule not found error, some smiles do not work in RDKit, so we just make them all zeros

**Comment by hima111997** [comment]
would not converting them to zeros affect the aggregated results (using default aggregation)?
