### ISSUE TITLE
pretrained model not found

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#38]
![image](https://user-images.githubusercontent.com/55895327/97786096-d57f8e80-1bb1-11eb-8f47-99feaf615176.png)

i tried to download them manually using wget on colab using the link in the code

![image](https://user-images.githubusercontent.com/55895327/97786119-09f34a80-1bb2-11eb-955f-19fcc688d584.png)

I tried to open the link and gave me this

![image](https://user-images.githubusercontent.com/55895327/97786752-5ccf0100-1bb6-11eb-8417-6d102fe9ec49.png)

**Comment by kexinhuang12345** [comment]
hi, we recently changed the pretrained model data server. Please pull the recent github repo. If you want to the download the link directly, you can use this link: https://dataverse.harvard.edu/api/access/datafile/4159682

**Comment by hima111997** [comment]
this is the code in virtual_screening function inside oneliner.py after I pulled the repository.
The problem occurs when I try to use virtual_screening not repurpose
![image](https://user-images.githubusercontent.com/55895327/97789672-faccc680-1bca-11eb-810d-7f5f1df53916.png)

**Comment by kexinhuang12345** [comment]
hey, you are right, I must have forgotten to modify that one. just fixed it in the recent commit: https://github.com/kexinhuang12345/DeepPurpose/commit/fde5b0c78436ba92d63e65f563ef0f72d3882624

**Comment by hima111997** [comment]
Okay thanks

Sent from Yahoo Mail on Android 
 
  On الاثنين, نوفمبر ٢, ٢٠٢٠ at ٤:١٢ ص, Kexin Huang<notifications@github.com> wrote:   


hey, you are right, I must have forgotten to modify that one. just fixed it in the recent commit: fde5b0c
