### ISSUE TITLE
What is the limit of a good binding score?

### ISSUE THREAD

**Issue by hima111997** [kexinhuang12345/DeepPurpose#42]
Hi!
I have used the deeppurpose library to screen a database and now I want to select the best binding drugs based on the binding score. 
Is there a limit for binding score below which I can select the drugs?

Thanks

**Comment by kexinhuang12345** [comment]
Hi, it really depends on the units. For the pre-trained model, we use Kd. So one choice would be less than 100nM, the smaller the safer.

**Comment by hima111997** [comment]
Okay thank you

Sent from Yahoo Mail on Android 
 
  On الاثنين, نوفمبر ٩, ٢٠٢٠ at ٨:٤١ م, Kexin Huang<notifications@github.com> wrote:   


Hi, it really depends on the units. For the pre-trained model, we use Kd. So one choice would be less than 100nM, the smaller the safer.
