### ISSUE TITLE
error when load pretrained model

### ISSUE THREAD

**Issue by xnuohz** [kexinhuang12345/DeepPurpose#43]
Error is `AttributeError: 'DBTA' object has no attribute 'lower'`
And my code is
```
config = utils.generate_config(
    drug_encoding='CNN',
    target_encoding='CNN',
    result_folder='DeepPurpose_model/Human/DeepDTA/d/0',
    **model_settings['DeepDTA']['config']
)

model = models.model_initialize(**config)
model = models.model_pretrained('DeepPurpose_model/Human/DeepDTA/d/0', model)
print(model)
```

**Comment by kexinhuang12345** [comment]
Hi, to use model_pretrained(), the input should be either a model path or a model name. To use model name, you can do `model = models.model_pretrained(model = 'MPNN_CNN_BindingDB')`. to use model path, you can do `model = models.model_pretrained('DeepPurpose_model/Human/DeepDTA/d/0')`

**Comment by xnuohz** [comment]
Got it, thank you so much:)

**Comment by xnuohz** [comment]
btw, I think it is necessary to return the predicted value in `DBTA.test_()`, so that when there is new data, it is easy to get their predicted value but not only the evaluation metrics.

**Comment by kexinhuang12345** [comment]
you can call `model.predict(df_data)` to do that where df_data is the output of the data processing function.

**Comment by xnuohz** [comment]
What is the correct format for prediction? The following format does not work while I call `model.predict(test_df)`
| drug_encoding | target_encoding | Label |
| :-: | :-: | :-: |
|  C1COCCO1 | MSTSSLRRQMKNIVHNYSEAEIKVREATSNDPWGPSSSLMSEIADL... | 1 |
