### ISSUE TITLE
how to replace the smiles or protein vocabulary

### ISSUE THREAD

**Issue by xnuohz** [kexinhuang12345/DeepPurpose#44]
I got `ValueError: Found unknown categories ['@'] in column 0 during transform` when I called `model.predict(test_df)`

**Comment by kexinhuang12345** [comment]
could you provide the file for `test_df`? it should be good since DeepPurpose uses ? to replace token that is not included in the vocab.

**Comment by xnuohz** [comment]
I use rdkit to convert smiles into a right format suitable for DeepPurpose. And the data file is [here](https://github.com/lifanchen-simm/transformerCPI/tree/master/Human%2CC.elegans/dataset)

**Comment by xnuohz** [comment]
what is the right dataframe format for dti prediction? i used the following data and it got error.
| drug_encoding | target_encoding | Label |
| :-: | :-: | :-: |
| CCC1(O)CC2c3cc(OC)c(OC)cc3CCN2CC1CC(C)C | MSPLNQSAEGLPQEASNRSLNATETSEAWDPRTLQALKISLAVVLS... | 0 |

**Comment by kexinhuang12345** [comment]
Hi, it seems the data column name is wrong. Also, the input for the DeepPurpose data is arrays. Please see this tutorial: https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/load_data_tutorial.ipynb

**Comment by xnuohz** [comment]
it seems i need to use `utils.data_process` to preprocess the dataframe

**Comment by kexinhuang12345** [comment]
Yes, if you want to use the encoders, you have to feed the data into the data_process function to obtain the desirable input encoding format.
