### ISSUE TITLE
Filename Issue in Tutorial_2_Drug_Property_Pred_Assay_Data.ipynb

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/DeepPurpose#48]
Hi Kexin,

There is an issue on loading the HIV data. After I ran the following commands:

```
X_drugs, y, drugs_index = dataset.load_HIV(path = './data')
print('Drug 1: ' + X_drugs[0])
print('Score 1: ' + str(y[0])
```

It gave me an error about FileNotFoundError.

The code /DeepPurpose/dataset.py tried to fin the file hiv.csv under data folder. However, after unzipping the hiv.zip file, it results in the HIV.csv file. Therefore, there is a name mismatch issue here (hiv.csv vs HIV.csv).

Afterward, I changed the filename from HIV.csv to hiv.csv, and it stopped getting me the filename error.

Best,
Ken

**Comment by kexinhuang12345** [comment]
Hey, good catch, there was a data server change in the last month so there might be some data files get messed up. Would you like to do a PR for it? or I can also change it now. Let me know!

Also, we have released another project [TDC](https://github.com/mims-harvard/TDC), with much more datasets of DTI, ADME,T, HTS and so on. It is also integrated with DeepPurpose framework, check out this [tutorial](https://github.com/mims-harvard/TDC/blob/master/tutorials/TDC_104_ML_Model_DeepPurpose.ipynb)

**Comment by pykao** [comment]
Hi Kexin, I did a PR. Thanks :)
