### ISSUE TITLE
Will you have a plan to implement DeepSmiles and SELFIES?

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#49]
https://github.com/baoilleach/deepsmiles
https://github.com/aspuru-guzik-group/selfies

Thank you so much for your great work!

**Comment by kexinhuang12345** [comment]
Hi, thanks for the pointers. We couldn't do not have the bandwidth to do that in the near month. But feel free to open up a PR. We have provided [instruction](https://github.com/kexinhuang12345/DeepPurpose/blob/master/CONTRIBUTE.md) to include new models. I have also added to the backlog.

**Comment by xuzhang5788** [comment]
Thank you. I hope somebody would like to implement them in the near future.
