### ISSUE TITLE
Pre-train Transformer of Drug

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/DeepPurpose#53]
Dear Kexin,

According to MT-DTI paper, they pre-trained the transformer on 97,092,853 molecules with canonical SMILES from PubChem. I just curious if I call `drug_encoding='Transformer'`, does your code use the pre-trained weights?

Thank you for your answering.

Best,
Po-Yu Kao

**Comment by kexinhuang12345** [comment]
Hi Po-Yu, the current version is not implemented with MT-DTI (as I believe it is implemented with TF while DeepPurpose is PyTorch). Instead, it is the basic transformer encoder block with substructure fingerprint (not pretrained) from our MolTrans [paper](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa880/5929692)
