### ISSUE TITLE
Did you fine tune every model? 

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#54]
Thank you so much for your great repo. From your demos, you always set epochs=100 for training. If we want to use some of the models, do we need to fine tune the hyperparameters and retrain them?

**Comment by kexinhuang12345** [comment]
Hi, ideally, i found depending on different dataset and task, the models are somewhat parameters sensitive. I would suggest do hyperparameter searching for individual use case. We also provide a tutorial on Bayesian Hyperparameter search in the demo: https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/Drug_Property_Pred-Ax-Hyperparam-Tune.ipynb

**Comment by kexinhuang12345** [comment]
the 100 epochs are following DeepDTA's implementation. But for small dataset, I usually find convergence in 10-20 epochs

**Comment by xuzhang5788** [comment]
Thanks a lot

**Comment by xuzhang5788** [comment]
I want to try https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/Drug_Property_Pred-Ax-Hyperparam-Tune.ipynb, but I can't find the data

**Comment by kexinhuang12345** [comment]
Hi, the data is from mit ai cures, you have to send an email to get it: https://www.aicures.mit.edu/forum

Checkout the open data section in https://www.aicures.mit.edu/data

**Comment by pykao** [comment]
Hi Kexin, do you have any reference paper for Bayesian hyper-parameter search?

**Comment by kexinhuang12345** [comment]
Hi, this is a good description of the BO using by Ax platform: https://ax.dev/docs/bayesopt.html

**Comment by chemlove** [comment]
> Hi, the data is from mit ai cures, you have to send an email to get it: https://www.aicures.mit.edu/forum
> 
> Checkout the open data section in https://www.aicures.mit.edu/data

Kexin, many thanks for this library!
It seems the CAPTCHA of https://www.aicures.mit.edu/forum can not be loaded now. So I can't get the data through email. 
Can you upload the aicures_data dataset since it is used in several demo ipynb files?
