### ISSUE TITLE
Do you include MolTrans in this repo

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#55]
You have another DTI repo called MolTrans. I think you didn't include this model in this toolkit, am I right? If not, what is the difference between DTI model of MolTrans and other models in this repo. Which one is better? Thanks a lot.

**Comment by kexinhuang12345** [comment]
Hi, currently, it is not included. MolTrans should have a better predictive performance for DTI but it has more complicated model architectures and also takes lots of time to train and tune hyperparameters. DeepPurpose is designed for fast prototyping and also supports Drug property, protein function, DDI, PPI predictions. It is for direct downstream use. The model architectures are also very simple (encoder-decoder framework).

**Comment by kexinhuang12345** [comment]
So, depends on your use case. If it is for industry use, I would recommend DeepPurpose. If it is for research benchmarking, you could include both DeepPurpose and MolTrans.

**Comment by xuzhang5788** [comment]
Thank you

**Comment by xuzhang5788** [comment]
I found you still have an option of embedding method as transformer both for drug and protein. Are they different from MolTrans? Can I choose the transformer option for the drug or protein embedding method? Thanks

**Comment by kexinhuang12345** [comment]
Hi, they are different. Since MolTrans has a specific decoder with interaction map + CNN.

**Comment by xuzhang5788** [comment]
Thank you. Actually, I tried your MolTrans, but I got errors. If you have time, please visit MolTrans repo. Hope to get your response. Thanks a lot.

**Comment by kexinhuang12345** [comment]
Oh thanks for the reminder. somehow i didn't receive notification for that repo. I will checkout in the next two days.
