### ISSUE TITLE
Missing models.py

### ISSUE THREAD

**Issue by AckerDWM** [kexinhuang12345/DeepPurpose#60]
Cool package! The models.py file seems to be missing from master, so `from DeepPurpose import models` doesn't work.

**Comment by kexinhuang12345** [comment]
Hey, thanks! DeepPurpose was originally for DTI only, but now we extend to multiple tasks. So now, to import the models class, you can do `from DeepPurpose import DTI` instead where you can replace DTI with DDI, PPI, CompoundPred, ProteinPred for your task. Also, just updated the main README, good catch!

**Comment by AckerDWM** [comment]
Thanks for the quick reply. Nice work!
