### ISSUE TITLE
Convert from nM to p

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/DeepPurpose#62]
Hi,

I am confused on your convert_y_unit function. I think this function mainly convert Kd to pKd, and convert pKd back to Kd. However, why do not you just use `y = -np.log10(y*1e-9)` here?

```
def convert_y_unit(y, from_, to_):
	# basis as nM

	if from_ == 'nM':
		y = y
	elif from_ == 'p':
		y = 10**(-y) / 1e-9

	if to_ == 'p':
		y = -np.log10(y*1e-9 + 1e-10)
	elif to_ == 'nM':
		y = y

	return y

print(convert_y_unit(convert_y_unit(100, 'p', 'nM'), 'nM', 'p'))
print(convert_y_unit(convert_y_unit(100, 'nM', 'p'), 'p', 'nM'))
print(convert_y_unit(100, 'p', 'p'))
print(convert_y_unit(100, 'nM', 'nM'))
```

It gave me:

```
10.0
100.09999999999994
10.0
100
```

I think the answers should be 100 for those four different combinations of convert_y_unit functions. 

What is the purpose to add  `1e-10` in the log function?

Best,
Ken

**Comment by kexinhuang12345** [comment]
Hi thanks for spotting this, it indeed looks weird. Don't remember why we added this, but do you want to make a PR to change it?

**Comment by pykao** [comment]
I just made a pull request to change the function.
