### ISSUE TITLE
The latest version of BindingDB

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/DeepPurpose#67]
Hi,

I think the BindingDB version you used in this repo is BindingDB_All_2020m2. Would you mind to use version BindingDB_All_2020m10? I can make a PR if you think this is a good idea?

Best,
Ken

**Comment by kexinhuang12345** [comment]
Yeah, sure that would be great! I am not sure if there is change on the
data org or it is just simply adding more data point. But yes, if you can
make a PR, that would be great, thanks!

On Sun, Dec 20, 2020 at 19:32 Po-Yu Kao <notifications@github.com> wrote:

> Hi,
>
> I think the BindingDB version you used in this repo is
> BindingDB_All_2020m2. Would you mind to use version BindingDB_All_2020m10?
> I can make a PR if you think this is a good idea?
>
> Best,
> Ken
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kexinhuang12345_DeepPurpose_issues_67&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=QS5AGu7ANMGvgpPxCU7qH2rJZInOWwYLpe7VSmo9QSc&s=ZsuuPhJLj_B8QNQ90SFjKxD-cabifbTsnxQxcq6-7u4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGUB5A7PH7UGV5JYW5BWN63SV26VZANCNFSM4VDUHQ4A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=QS5AGu7ANMGvgpPxCU7qH2rJZInOWwYLpe7VSmo9QSc&s=m6VecGC9I8elzjNXlcGxPNSRJdmay_aCtB2gxtw5mL0&e=>
> .
>
-- 

Best Regards,

*Kexin Huang*

New York University
Mobile (USA): +1 917-558-1909
Email: kexin.huang@nyu.edu
