### ISSUE TITLE
Guideline for adding self-defined encoders

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/DeepPurpose#69]
Do you have a guideline for adding a self-defined encoder?

**Comment by futianfan** [comment]
Good question! I will discuss with Kexin about it. Thanks

**Comment by futianfan** [comment]
https://github.com/kexinhuang12345/DeepPurpose/blob/master/CONTRIBUTE.md 
this is the guidance on how to contribute to our repo, including adding the self-defined encoders.
thanks!
