### ISSUE TITLE
config params error

### ISSUE THREAD

**Issue by xnuohz** [kexinhuang12345/DeepPurpose#72]
Hi, it seems that the config in [demo](https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/MPNN_AAC_Davis.ipynb) cannot work now:(

I used the following cfg
```
'MPNNAACDTA': {
      'drug_encoding': 'MPNN',
      'target_encoding': 'AAC',
      'cls_hidden_dims': [1024, 1024, 512],
      'train_epoch': 100,
      'LR': 0.001,
      'batch_size': 128,
      'hidden_dim_drug': 128,
      'hidden_dim_protein': 128,
      'input_dim_protein': 128,
      'mlp_hidden_dims_target': [128],
      'mpnn_hidden_size': 128,
      'mpnn_depth': 3,
      'cnn_target_filters': [32, 64, 96],
      'cnn_target_kernels': [4, 8, 12]
  }
```
and it got the error `RuntimeError: mat1 dim 1 must match mat2 dim 0`

My DeepPurpose version is 0.0.5.

**Comment by kexinhuang12345** [comment]
Hi, I just ran that demo and it runs without errors. Could you send the scripts to obtain the errors? thx

**Comment by xnuohz** [comment]
Mail to you

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late reply. Could you send me the problem again? It seems like I didn't receive it. Thanks!

**Comment by kexinhuang12345** [comment]
It looks like somehow the AAC input_dim_protein is wrong, could you switch to 8420?

**Comment by kexinhuang12345** [comment]
closing for now, feel free to reopen
