### ISSUE TITLE
models importing issue

### ISSUE THREAD

**Issue by asadkhanmaharvi** [kexinhuang12345/DeepPurpose#77]
First of all I would like to appreciate your work , i am facing a little bit error in models importing from DeepPurpose other modules working fine of DeepPurpose.

from DeepPurpose import models

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-35ac80498fba> in <module>
----> 1 from DeepPurpose import models

ImportError: cannot import name 'models'

**Comment by kexinhuang12345** [comment]
Hi the models class is deprecated as we extend above multiple tasks. Where did you find this code? I can change the code to avoid future confusion. The old models class is now DTI class. To support the same code you could replace it with 

`from DeepPurpose import DTI as models`

**Comment by asadkhanmaharvi** [comment]
Thank you for your positive and quick response. I have found it from the Pip Installation source https://pypi.org/project/DeepPurpose/.
