### ISSUE TITLE
Error when I chose 'ErG' as my drug_encoding

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#81]
After I changed drug_encoding from 'cnn' to ErG' in "DeepDTA_Reproduce_KIBA.ipynb",
when I ran this cell
model.train(train, val, test)
I got:

AttributeError                            Traceback (most recent call last)
<ipython-input-7-b77870d489ea> in <module>
----> 1 model = models.model_initialize(**config)
      2 model.train(train, val, test)

~/projects/DeepPurpose/DeepPurpose/DTI.py in model_initialize(**config)
     57 
     58 def model_initialize(**config):
---> 59         model = DBTA(**config)
     60         return model
     61 

~/projects/DeepPurpose/DeepPurpose/DTI.py in __init__(self, **config)
    267                         self.model_drug = MPNN(config['hidden_dim_drug'], config['mpnn_depth'])
    268                 else:
--> 269                         raise AttributeError('Please use one of the available encoding method.')
    270 
    271                 if target_encoding == 'AAC' or target_encoding == 'PseudoAAC' or  target_encoding == 'Conjoint_triad' or target_encoding == 'Quasi-seq' or target_encoding == 'ESPF':

AttributeError: Please use one of the available encoding method.

**Comment by kexinhuang12345** [comment]
Hi, could you update to the newest version of DeepPurpose? ErG is just included in the latest version

**Comment by xuzhang5788** [comment]
I have updated DeepPurpose already with pip install DeepPuopose --upgrade. I also copied new utils.py to my folder. Before I did that, I couldn't go through cell 2. I don't know if you also changed other files.

**Comment by xuzhang5788** [comment]
I copied the new DTI.py into my DeepPurpose folder, and then upgraded DeepPurpose. Now it works.

**Comment by kexinhuang12345** [comment]
Yes, i think if you are using DeepPurpose inside a source folder, it will use the source DeepPurpose, which you could do git pull to update the current version.
