### ISSUE TITLE
How did you train MPNN_CNN_BindingDB_IC50?

### ISSUE THREAD

**Issue by pykao** [kexinhuang12345/DeepPurpose#82]
Hi, 

I am trying to train a MPNN/CNN model using around 1.2M IC50 interactions from BindingDB dataset (2021m0). However, the first problem I encountered was the memory issue of MPNN drug encoder. If I want to train the model with all interactions, I need to set MAX_ATOM = 700 that gives me the memory issue even if my server has 252GB memories. 

Do you know how did you solve this kind of issue to train the MPNN_CNN_BindingDB_IC50 successfully? Did you train the model with previous version (non-parallel) of MPNN drug encoder? Or, did you ignore those interactions with long SMILES sequence?

Best,
Ken Kao

**Comment by kexinhuang12345** [comment]
Hey, we used determined AI to train it. Let me ask if they have encountered any issue before but I think the code version is before the parallel GPU ones. We will also be working to fix this MPNN max issue in the coming month. I will get back to you!

**Comment by skviswa** [comment]
@kexinhuang12345 I checked the experiments and it looks like we have been able to train with both single and multi GPU configurations. @pykao I am not sure what all your relevant parameters look like aparat from MAX_ATOM and no of IC50 interactions, what your GPU configurations look like etc.  
I can try re-running an experiment based on what you are trying to run. @davetroiano looping you in for any further suggestion as well :)

**Comment by pykao** [comment]
```
import DeepPurpose.DTI as models                                                                                                 
from DeepPurpose.utils import *                                                                                                  
from DeepPurpose.dataset import *                                                                                                
from rdkit import Chem                                                                                                           
from rdkit.Chem import Draw                                                                                                      
                                                                                                                                  
X_drugs, X_targets, y = process_BindingDB(path = './data/BindingDB_All.tsv', df = None, y = 'IC50', binary = False, convert_to_log = True, threshold = 30)

drug_encoding = 'MPNN'
target_encoding = 'CNN'

train, val, test = data_process(X_drugs, X_targets, y, drug_encoding, target_encoding, split_method='random',frac=[0.7,0.1,0.2])

config = generate_config(drug_encoding = drug_encoding, target_encoding = target_encoding, cls_hidden_dims = [1024,1024,512], train_epoch = 150, test_every_X_epoch = 10, LR = 0.0005, batch_size = 128, hidden_dim_drug=128, mpnn_hidden_size=128, mpnn_depth=3, cnn_target_filters = [32, 64, 96], cnn_target_kernels = [4, 8, 12])

model = models.model_initialize(**config)
model.train(train, test, test)

model.save_model('./model/model_MPNN_CNN/')
```

I downloaded the latest version of BindingDB 

```url = 'https://www.bindingdb.org/bind/downloads/BindingDB_All_2021m0.tsv.zip'```

and set `MAX_ATOM=700`

I have 252G memory  and 4 1080 Ti (11178MiB) and 2 2080 Ti (11019MiB) in our server.

Thank you for your help @kexinhuang12345 @skviswa @davetroiano . :)

**Comment by kexinhuang12345** [comment]
Hi @pykao, I think it is due to the new data issue. For the dataset in the last version, it works fine. Maybe some data in the new version has super long SMILES strings? I would actually remove them since this could make the model pad to 700 atoms for majority of the small molecules, which lead to much slower training and require large memory. This also raises a good question though, because the current version is a dense implementation (pad to max atoms), it leads to inscalability. We would see how to put in a new efficient MPNN model. For the time being, could you try removing these points and reduce the 700 max atoms?

**Comment by kexinhuang12345** [comment]
closing for now, feel free to reopen!
