### ISSUE TITLE
Is it possible to combine two or more drug encoding to one encoding?

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#86]
For each drug encoding, you allow to choose one, such as Morgan, or Pubchem, or other encoding methods. I want to try combine two of them at the beginning and then train the model. For example, I choose Morgan and Pubchem as drug the encoding methods. For Morgan and Pubchem, I will get 1024-dimensional and 881-dimensional features. I want to concatenate them to become 1905-dimensional features as the drug encoding and then start to train the models. For protein, the same things. Thanks

**Comment by kexinhuang12345** [comment]
Hi, that's a good point. But it is not obvious to me to easily write code for that without making significant changes to the code structures. Basically, DeepPurpose assumes one encoder for drug and one for proteins.

**Comment by kexinhuang12345** [comment]
An easy workaround is to obtain the embedding and then concatenate them and feed them into MLP from sklearn.
