### ISSUE TITLE
Is there a tutorial about read_file_training_dataset_protein_proteins_pairs()?

### ISSUE THREAD

**Issue by SteventheExorcist** [kexinhuang12345/DeepPurpose#90]
Hello. I cannot find it in the dataset tutorial when I am trying to run the PPI program. Is there a tutorial. Thanks a lot!

**Comment by kexinhuang12345** [comment]
Hi, I don’t think there is a tutorial. But it should be pretty similar to
the other tasks. There is an example in the GitHub read me file. Maybe
start from there?

On Fri, Feb 26, 2021 at 20:39 tachyon299792458 <notifications@github.com>
wrote:

> Hello. I cannot find it in the dataset tutorial when I am trying to run
> the PPI program. Is there a tutorial. Thanks a lot!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kexinhuang12345_DeepPurpose_issues_90&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=fqIVn1jbvIZ0OgVNRHc574URlKFoEcoFprVuY82skA8&s=R6P9jOY9d3VOMM4gVyiXlRinVyBc6orWklHk_dnKdJU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGUB5A6EUQ36QVGCUTGGAB3TBBZQXANCNFSM4YJRK5YQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=pm9TebsFk47J6Yqy4-ntKg&m=fqIVn1jbvIZ0OgVNRHc574URlKFoEcoFprVuY82skA8&s=-kb-74YaaiRWSB9VTlZ3zvAColQAJe7pDWVGWmkNexo&e=>
> .
>
-- 

Best Regards,

*Kexin Huang*

New York University
Mobile (USA): +1 917-558-1909
Email: kexin.huang@nyu.edu

**Comment by kexinhuang12345** [comment]
An example: 

```python
from DeepPurpose import PPI as models
from DeepPurpose.utils import *
from DeepPurpose.dataset import *

# load DB Binary Data
X_targets, X_targets_, y = read_file_training_dataset_protein_proteins_pairs()

target_encoding = 'CNN'
train, val, test = data_process(X_target = X_targets, X_target_ = X_targets_, y = y, 
			    target_encoding = target_encoding,
			    split_method='random', 
			    random_seed = 1)

config = generate_config(target_encoding = target_encoding, 
                         cls_hidden_dims = [512], 
                         train_epoch = 20, 
                         LR = 0.001, 
                         batch_size = 128,
                        )

model = models.model_initialize(**config)
model.train(train, val, test)
```
