### ISSUE TITLE
Not able to import modules on colab

### ISSUE THREAD

**Issue by AnushaSRao** [kexinhuang12345/DeepPurpose#92]
Hello,
I was trying to run DeepPurpose on colab. I have followed the same steps mentioned in the colab notebook present in README https://colab.research.google.com/drive/1eF60BwGX6PnB91vpx5dRxFa72e6-MYuZ?usp=sharing

There is no error in the installation procedure. But i am not able to import anything. 
ImportError                               Traceback (most recent call last)
<ipython-input-44-3550f156572d> in <module>()
----> 1 from DeepPurpose import utils

ImportError: cannot import name 'utils'

**Comment by kexinhuang12345** [comment]
Hi, can you send your colab notebook?

**Comment by yoonaeko082** [comment]
I got same error. 
https://colab.research.google.com/drive/1jD4dWx1vxM1te7hlBH4hE3YrfyxpbNCG?usp=sharing

After installing DeepPurpose, I have put 'play.py' at /centent/DeepPurpose/ generating with 'three line codes' provided.
Then, I could have the result of the model prediction using toyset. 
However, I tried to import DeepPurpose for my own code, there's an error as same as above.

**Comment by AnushaSRao** [comment]
> Hi, can you send your colab notebook?

https://colab.research.google.com/drive/1-ocqP9h-FHTMt7L_CtmkE-wi9QAPZ7Su?usp=sharing

**Comment by kexinhuang12345** [comment]
it seems it is working in the bash environment but not in notebook code blocks. I guess it maybe issues with the sys path. I will take a look later this week. I haven't used colab before, in the meantime, @hima111997 do you have any quick workaround for this?

**Comment by hima111997** [comment]
@AnushaSRao @yoonaeko082 you need first to change directory to the DeepPurpose folder containing the .py (utils.py , etc...) files

Sent from Yahoo Mail on Android 
 
  On الثلاثاء, مارس ١٦, ٢٠٢١ at ٢:٤٠ ص, Kexin ***@***.***> wrote:   


it seems it is working in the bash environment but not in notebook code blocks. I guess it maybe issues with the sys path. I will take a look later this week. I haven't used colab before, in the meantime, @hima111997 do you have any quick workaround for this?

**Comment by AnushaSRao** [comment]
@hima111997 Thank you so much for the help. I put my code in a .py file instead of running it using Jupyter cell. And it worked!

**Comment by hima111997** [comment]
@AnushaSRao You are Welcome

**Comment by kexinhuang12345** [comment]
Thanks! Closing for now!
