### ISSUE TITLE
[feature-request] Select GPU 

### ISSUE THREAD

**Issue by agamemnonc** [kexinhuang12345/DeepPurpose#94]
Hey, many thanks for this library!

Just a suggestion, I believe it would be really handy to be able to explicitly specify which GPU(s) to use for training/inference.

**Comment by kexinhuang12345** [comment]
Hey, thanks for the suggestion and kind words! Make sense and I would add it soon!

**Comment by kexinhuang12345** [comment]
hey, you can now specify cuda_id as a variable for specific cuda device
