### ISSUE TITLE
[Question] Drug and protein encoding

### ISSUE THREAD

**Issue by albertma-evotec** [kexinhuang12345/DeepPurpose#97]
There are 10 drug encoding and 8 protein encoding. Does it mean there are 80 possible combination of encodings one could use for their model? Would some of the combination does not make sense or wont work at all?
Thanks

**Comment by kexinhuang12345** [comment]
Hi, yes exactly, all combinations should work. Various combination would prob look at different signals. so it would be great to try some of them out and aggregate the predictions
