### ISSUE TITLE
[Question] Enantiomeric/Stereoisomeric compounds

### ISSUE THREAD

**Issue by albertma-evotec** [kexinhuang12345/DeepPurpose#98]
Are the encoding protocols sensitive to enantiomeric and stereoisomeric compounds?
It matters because two isomers have different binding affinities. If they are going to have exactly the same encoding, it may cause problem in training.

**Comment by kexinhuang12345** [comment]
Hi, it depends on the encoding schemes. For SMILES strings encoding, it should be sensitive as long as the SMILES string is sensitive and the training/testing set both have the same encoding scheme. But for molecular graph (MPNN), it is not. It is actually one of an active research directions to put chirality into the graph neural network: https://arxiv.org/abs/2012.00094
