### ISSUE TITLE
[bug] pearson_r p-value

### ISSUE THREAD

**Issue by albertma-evotec** [kexinhuang12345/DeepPurpose#99]
In your DBTA.train() function in DTI.py file

```
     if verbose:
         print('Validation at Epoch '+ str(epo + 1) + ' with loss:' + str(loss_val.item())[:7] +', MSE: ' + str(mse)[:7] + ' , Pearson Correlation: '
	+ str(r2)[:7] + ' with p-value: ' + str(p_val)[:7] +' , Concordance Index: '+str(CI)[:7])
```

the p-value is often a very small number so that it is represented as the scientific e notation, i.e like 1.23456789e-9 
str() it then [:7] will miss the e number part and lead to a wrong result.

str(1.23456789e-9)[:7]   ->   1.23456      not what you actually wanted!

**Comment by kexinhuang12345** [comment]
good point! do you want to make a pr to fix it? i can also do that; let me know!

**Comment by albertma-evotec** [comment]
I have written quite a bit of codes for my personal needs so dont really want to mix this up with your main branch.

I believe a small change like this should always keep the number as a string of length 7.
str(p_val)[:7]    ->     str(f"{p_val:.2E}")

Really appreciated your prompt reply!

**Comment by kexinhuang12345** [comment]
Great! Thanks, i will make the change shortly!
